config/routes.rb
Rails.application.routes.draw do
  resources :companies, except: [:new, :create]
  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies, only: [:show] do
    resources :positions, except: [:new, :create]
  end

  resources :users, only: [:show] do
    resources :checklists, except: [:show, :new]
  end

  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

#Routes for Google authentication
  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  #get 'auth/failure', to: redirect('/')

  #get '*path' => redirect('/')
  resources :positions, only: [:new, :create]
  get '/positions', to: 'positions#all_index'
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  has_many :checklists
  accepts_nested_attributes_for :company
  has_many :users, through: :checklists
  validates :title, :description, :salary, presence: true

  def self.sort_by_title
    order('LOWER(title)')
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :require_login

  def index
    @company = Company.find_by(id: params[:company_id])
    if @company.nil?
      redirect_to companies_path
    else
    @positions = @company.positions
      respond_to do |format|
        format.html { render :index}
        format.json { render json: @positions}
      end
    end
  end

  def all_index
    @positions = Position.sort_by_title
    respond_to do |format|
      format.html { render :all_index }
      format.json { render json: @positions }
    end
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)

    if params[:position][:company_id]
      @position.company_id = params[:position][:company_id]
    end

    if @position.save
      respond_to do |format|
        format.html { redirect_to company_position_path(@position.company, @position) }
        format.json { render json: @position}
      end
    else
      render :new
    end
  end

  def show
    @position = Position.find_by(id: params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @position }
    end
  end

  def edit
    @position = Position.find_by(id: params[:id])
  end

  def update
    @position = Position.find_by(id: params[:id])
    if params[:position][:company_attributes][:name].empty?
       @position.update(title: params[:position][:title], description:  params[:position][:description], salary:  params[:position][:salary], full_time:  params[:position][:full_time], company_id: params[:position][:company_id])
      redirect_to company_position_path(@position.company, @position)
    elsif !params[:position][:company_attributes][:name].empty?
      @position.update(position_params)
      redirect_to company_position_path(@position.company, @position)
    else
      render :edit
    end
  end

  private
    def position_params
      params.require(:position).permit(:title, :description, :salary, :full_time, :company_id, :company_attributes => [:name, :url, :description])
    end

    # def with_company_params
    #     params.require(:position).permit(:title, :description, :salary, :full_time,:company_attributes => [:name, :url, :description])
    # end
    #
    # def test_params
    #     params.require(:position).permit(:title, :description, :salary, :full_time, :company_id)
    # end

end

app/helpers/positions_helper.rb
module PositionsHelper
  
end

app/views/positions/_form.html.erb
<div class="my-4">
<% if @position.errors.any? %>
  <% @position.errors.full_messages.each do |message| %>
  <ul>
    <li class="text-danger"><%= message %></li>
  </ul>
  <% end %>
<% end %>
</div>

<%= form_for [company, @position] do |f| %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control w-50" %>
  </div>

  <div class="form-group">
    <%= f.label "Description" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Annual Salary" %><br>
    <%= f.number_field :salary, class: "form-control w-25" %>
  </div>

  <div class="form-group">
    <%= f.label "Is this a full time position?" %>
    <%= f.check_box :full_time %>
  </div>

  <h5>CHOOSE OR CREATE A COMPANY FOR THIS POSITION:</h5>

  <label>Select a Company</label>
    <%#= f.hidden_field :position_id, value: @position.id %>
    <%= f.collection_select :company_id, Company.all, :id, :name, {prompt: "Select"}, class: "form-control my-1 w-25" %>
<br>

  <a href="#" id="js-create-company-btn">Or Create a new Company</a>
  <div id="js-new-company" style="display:none;">

    <%= f.fields_for :company, @position.build_company do |company_f| %>

    <div class="form-group">
      <%= company_f.label :name %>
      <%= company_f.text_field :name, class: "form-control w-50" %>
    </div>

    <div class="form-group">
      <%= company_f.label :url %>
      <%= company_f.text_field :url, class: "form-control w-25" %>
    </div>

    <div class="form-group">
      <%= company_f.label :description %>
      <%= company_f.text_area :description, class: "form-control" %>
    </div>
    <% end %>
  </div>

  <div>
  <%= f.submit class: "btn btn-info mt-5" %>
  </div>
<% end %>

<div class="my-5">
  <%= link_to 'Back', url_for(:back) %>
</div>

app/views/positions/all_index.html.erb
<h1 class="my-5">FIND POSITIONS</h1>

<p class="text-danger my-4"><%= flash[:message] %></p>

<p>&#10038; Can't find a position? You can create from <%= link_to "here", new_position_path %></p>

<input id="js-value" type="text" />
<button id="js-sort" class="btn btn-info btn-sm" data-userid="<%= current_user.id %>">Search</button>
<%= link_to "All", positions_path, class: "btn btn-outline-info btn-sm" %>

<table class="table table-borderless sm-font">
  <thead class="thead-light">
    <tr>
      <th scope="col">Position</th>
      <th scope="col">Company</th>
      <th scope="col">Description</th>
      <th scope="col">Salary</th>
      <th scope="col">Full Time</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody id="sorted-table">
    <% @positions.each do |position| %>
      <tr class="js-tr" data-id="<%= position.id %>">
      <td class="js-position-title"><%= link_to position.title, company_position_path(position.company, position) %></td>
      <td><%= link_to position.company.name, company_path(position.company) %></td>
      <td><%= link_to (truncate position.description), "#", class: "js-truncate link-#{position.id}", data: {id: position.id, companyid: position.company_id} %></td>
      <td><%= display_salary(position.salary) %></td>
      <td><%= display_check(position.full_time) %></td>
      <td>
        <%= button_to user_checklists_path(current_user.id), class: "btn btn-success btn-sm sm-font", data: {confirm: "You want to add this position to your list?"} do %>
        Add to my checklist
          <input type="hidden" name="checklist[company_id]" value="<%= position.company_id %>">
          <input type="hidden" name="checklist[position_id]" value="<%= position.id %>">
        <% end  %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-5">
  <%= link_to "Create a new position", new_position_path, class: "btn btn-info btn-sm"  %>

  <%= link_to "Check all companies", companies_path, class: "btn btn-info btn-sm" %>

</div>

<div class="my-5">
  <%= link_to 'Back', url_for(:back) %>
</div>

app/views/positions/edit.html.erb
<h2 class="my-5">EDIT THE POSITION</h2>
<%= render partial: "form", locals: {company: @position.company} %>

app/views/positions/index.html.erb
<h1 class="mt-5"><%= link_to display_title(@company.name), company_path(@company) %></h1>

<p class="text-danger my-4"><%= flash[:message] %></p>
<table class="table table-borderless sm-font">
  <thead class="thead-light">
    <tr>
      <th scope="col">Position</th>
      <th scope="col">Description</th>
      <th scope="col">Salary</th>
      <th scope="col">Full Time</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
      <td><%= link_to position.title, company_position_path(@company, position) %></td>
      <td><%= link_to (truncate position.description), "#", class: "js-truncate link-#{position.id}", data: {id: position.id, companyid: position.company_id} %></td>
      <td><%= display_salary(position.salary) %></td>
      <td><%= display_check(position.full_time) %></td>
      <td>
        <%= button_to user_checklists_path(current_user.id), class: "btn btn-success btn-sm sm-font", data: {confirm: "You want to add this position to your list?"} do %>
        Add to my checklist
          <input type="hidden" name="checklist[company_id]" value="<%= position.company_id %>">
          <input type="hidden" name="checklist[position_id]" value="<%= position.id %>">
        <% end  %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-5">
  <%= link_to "Create a new position", new_position_path, class: "btn btn-info btn-sm"  %>

  <%= link_to "Check all companies", companies_path, class: "btn btn-info btn-sm" %>

  <% if !@company.positions.empty? %>
    <%= link_to "Go to your checklist", user_checklists_path(current_user), class: "btn btn-info btn-sm" %>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to "Edit company", edit_company_path(@company), class: "btn btn-warning btn-sm" %>
  <% end %>
</div>

<div class="my-5">
  <%= link_to 'Back', url_for(:back) %>
</div>

app/views/positions/new.html.erb
<h2 class="my-5">CREATE A POSITION</h2>

<%= render partial: "form", locals: {company: @company} %>

app/views/positions/show.html.erb
<h2 class="mt-5"><%= @position.title %></h2>
<p><%= link_to @position.company.name, company_positions_path(@position.company) %></p>

<div class="mt-5">
  <h4>Job Desciption</h4>
  <p><%= @position.description %></>

  <h4>Salary</h4>
  <p><%= display_salary(@position.salary) %></p>
  <h4>Job Type</h4>
  <p><%= display_job_type(@position.full_time) %></p>

  <h4>Position created at</h4>
  <p><%= display_time(@position.created_at) %></p>

  <h4>Position updated at</h4>
  <p><%= display_time(@position.updated_at) %></p>

</div>

<div class="mt-5">
  <%= button_to user_checklists_path(current_user.id), class: "btn btn-success mb-3", data: {confirm: "You want to add this position to your list?"} do %>
    Add to my checklist
    <input type="hidden" name="checklist[company_id]" value="<%= @position.company_id %>">
    <input type="hidden" name="checklist[position_id]" value="<%= @position.id %>">
  <% end  %>

  <% if current_user.admin? %>
    <%= link_to "Edit this position", edit_company_position_path(@position.company, @position), class: "btn btn-outline-warning" %>
  <% end %>
</div>

<div class="my-5">
  <%= link_to 'Back', url_for(:back) %>
</div>