config/routes.rb
Rails.application.routes.draw do
  resources :companies, except: [:new, :create]
  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies, only: [:show] do
    resources :positions, except: [:new, :create]
  end

  resources :users, only: [:show] do
    resources :checklists, except: [:show, :new]
  end

  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

#Routes for Google authentication
  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  #get 'auth/failure', to: redirect('/')

  #get '*path' => redirect('/')
  resources :positions, only: [:new, :create]
  get '/positions', to: 'positions#all_index'
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :user
  belongs_to :position
  belongs_to :company

  def self.sort_by_resume
    order(resume: :desc)
  end

  def self.find_position(params)
    where(["user_id = ? AND position_id = ?", params[:user_id], params[:checklist][:position_id]]).first_or_initialize  do |checklist|
      checklist.user_id = params[:user_id]
      checklist.position_id = params[:checklist][:position_id]
      checklist.company_id = params[:checklist][:company_id]
    end
  end




end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :require_login

  def index
    @user = User.find_by(id: params[:user_id])
    @user ? @checklists = @user.checklists : page_not_found
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @checklists }
    end
  end

  def create
    company = Company.find_by(id: params[:checklist][:company_id])
    @user = User.find_by(id: params[:user_id])
    @checklist = Checklist.find_position(params)

    if @checklist.persisted?
      flash[:message] = "This position is already in your checklist."
      redirect_to user_checklists_path(@user)
    else
      @checklist.save
      respond_to do |format|
        format.html { redirect_to user_checklists_path(@user) }
        format.json { render json: @checklist }
      end

    end
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    if @user.id == session[:user_id]
      @checklist = Checklist.find_by(id: params[:id])
    else
      page_not_found
    end
  end

  def update
    #params[:user_id]
    checklist = Checklist.find_by(id: params[:id])
    checklist.update(checklist_params)
    redirect_to user_checklists_path(current_user)
  end

  def destroy
    checklist = Checklist.find_by(id: params[:id])
    checklist.destroy
    redirect_to user_checklists_path(current_user)
  end

  private
    def checklist_params
      params.require(:checklist).permit(:resume, :interview, :completed, :note, :company_id, :user_id, :position_id)
    end

    def page_not_found
      flash[:message] = "Oops. Page not found."
      redirect_to user_checklists_path(current_user)
    end

end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/edit.html.erb
<h1 class="my-5">Update <%= display_title(@user.username) %>'s Checklist</h1>

<%= form_for [@user, @checklist] do |f| %>
  <div class="form-check">
    <%= f.check_box :resume, class: "form-check-input" %>
    <%= f.label "Resume sent?", class: "form-check-label"  %>
  </div>

  <div class="form-check">
    <%= f.check_box :interview, class: "form-check-input" %>
    <%= f.label "Inteview done?", class: "form-check-label"  %>
  </div>

  <div class="form-check">
    <%= f.check_box :completed, class: "form-check-input" %>
    <%= f.label "All done?", class: "form-check-label" %>
  </div>

  <div class="form-group my-4">
    <%= f.label "Add Brief Note" %><br>
    <%= f.text_field :note, class: "form-control" %>
  </div

  <div>
    <%= f.submit class: "btn btn-info my-5" %>
  </div>
<% end %>

app/views/checklists/index.html.erb
<h2 class="mt-5"><%= display_title(current_user.username) %>'s CHECKLIST</h2>

<p class="text-danger my-4"><%= flash[:message] %></p>

<% if @checklists.empty? %>
  <p class="alert alert-warning my-4">Your checklist is empty now. <%= link_to "Find positions", positions_path, class: "btn btn-warning btn-sm" %></p>
<% end %>

<table class="table table-borderless sm-font">
  <thead class="thead-light">
    <tr>
      <th scope="col">Company</th>
      <th scope="col">Position</th>
      <th scope="col">Full Time</th>
      <th scope="col">Resume</th>
      <th scope="col">Interview</th>
      <th scope="col">Completed</th>
      <th scope="col">Note</th>
      <th scope="col">Last update</th>
      <th scope="col">Progress</th>
    </tr>
  </thead>

  <tbody>
    <% @checklists.each do |checklist| %>
    <tr>
      <td><%= link_to checklist.company.name, company_path(checklist.company) %>
      </td>
      <td><%= link_to display_title(checklist.position.title), company_position_path(checklist.company, checklist.position) %></td>
      <td><%= display_check(checklist.position.full_time) %></td>
      <td><%= display_check(checklist.resume) %></td>
      <td><%= display_check(checklist.interview) %></td>
      <td><%= display_check(checklist.completed) %></td>
      <td><%= checklist.note %></td>
      <td><%= display_time(checklist.updated_at) %></td>
      <td><%= link_to "update", edit_user_checklist_path(@user, checklist) %><br>
      <%= link_to "delete", user_checklist_path(@user, checklist), method: :delete, data: {confirm: "Are you sure? You want to remove from your list?"} %>
    <% end %>
    </tr>
  </tbody>
</table>

<div class="mt-5">
  <%= link_to "Check all positions", positions_path, class: "btn btn-info" %>
  <%= link_to "Check all companies", companies_path, class: "btn btn-info" %>
</div>