config/routes.rb
Rails.application.routes.draw do
  resources :companies, except: [:new, :create]
  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies, only: [:show] do
    resources :positions, except: [:new, :create]
  end

  resources :users, only: [:show] do
    resources :checklists, except: [:show, :new]
  end

  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

#Routes for Google authentication
  get '/auth/:provider/callback', to: 'sessions#googleAuth'
  #get 'auth/failure', to: redirect('/')

  #get '*path' => redirect('/')
  resources :positions, only: [:new, :create]
  get '/positions', to: 'positions#all_index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRailsJobSearchOrganizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/e216e93db1.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
        <% if !logged_in? %>
          <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link" %>
          <%= link_to "Log In", login_path, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "#{display_title(current_user.username)}'s profile", user_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "Company", companies_path, class: "nav-item nav-link" %>
          <%= link_to "Position", positions_path, class: "nav-item nav-link" %>
          <%= link_to "Checklist", user_checklists_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "Create", new_position_path, class: "nav-item nav-link" %>
          <%= link_to "Log Out", logout_path, method: :post, class: "nav-item nav-link" %>
        <% end %>
      </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="pt-2">
      <p class="sm-font">&copy; 2019 Job Search Organizer</p>
    </footer>

  </body>
</html>